# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Sebastian\PycharmProjects\can-ethernet-monitor\ui\disenos\designer\mainwindow.ui'
#
# Created: Thu Feb 25 12:57:24 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(870, 682)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.conectarWifi = QtGui.QPushButton(self.centralwidget)
        self.conectarWifi.setObjectName("conectarWifi")
        self.horizontalLayout_2.addWidget(self.conectarWifi)
        self.checkBoxWifi = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxWifi.setText("")
        self.checkBoxWifi.setObjectName("checkBoxWifi")
        self.horizontalLayout_2.addWidget(self.checkBoxWifi)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.conectarXBee = QtGui.QPushButton(self.centralwidget)
        self.conectarXBee.setObjectName("conectarXBee")
        self.horizontalLayout_2.addWidget(self.conectarXBee)
        self.checkBoxXbee = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxXbee.setText("")
        self.checkBoxXbee.setObjectName("checkBoxXbee")
        self.horizontalLayout_2.addWidget(self.checkBoxXbee)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.fecha = QtGui.QDateTimeEdit(self.centralwidget)
        self.fecha.setAlignment(QtCore.Qt.AlignCenter)
        self.fecha.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.fecha.setObjectName("fecha")
        self.horizontalLayout_2.addWidget(self.fecha)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.cargaBaterias = QtGui.QProgressBar(self.centralwidget)
        self.cargaBaterias.setProperty("value", 24)
        self.cargaBaterias.setObjectName("cargaBaterias")
        self.horizontalLayout_2.addWidget(self.cargaBaterias)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tab1 = QtGui.QTabWidget(self.centralwidget)
        self.tab1.setObjectName("tab1")
        self.tabGeneral1 = QtGui.QWidget()
        self.tabGeneral1.setObjectName("tabGeneral1")
        self.gridLayout_6 = QtGui.QGridLayout(self.tabGeneral1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame = QtGui.QFrame(self.tabGeneral1)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_14 = QtGui.QGridLayout(self.frame)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_14.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_43 = QtGui.QLabel(self.frame)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_13.addWidget(self.label_43)
        self.label_35 = QtGui.QLabel(self.frame)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_13.addWidget(self.label_35)
        self.label_36 = QtGui.QLabel(self.frame)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_13.addWidget(self.label_36)
        self.label_37 = QtGui.QLabel(self.frame)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_13.addWidget(self.label_37)
        self.horizontalLayout_7.addLayout(self.verticalLayout_13)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.timeEdit_3 = QtGui.QTimeEdit(self.frame)
        self.timeEdit_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeEdit_3.setReadOnly(True)
        self.timeEdit_3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.timeEdit_3.setObjectName("timeEdit_3")
        self.verticalLayout_12.addWidget(self.timeEdit_3)
        self.doubleSpinBox_23 = QtGui.QDoubleSpinBox(self.frame)
        self.doubleSpinBox_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_23.setReadOnly(True)
        self.doubleSpinBox_23.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_23.setSpecialValueText("")
        self.doubleSpinBox_23.setDecimals(1)
        self.doubleSpinBox_23.setMaximum(999.0)
        self.doubleSpinBox_23.setObjectName("doubleSpinBox_23")
        self.verticalLayout_12.addWidget(self.doubleSpinBox_23)
        self.doubleSpinBox_24 = QtGui.QDoubleSpinBox(self.frame)
        self.doubleSpinBox_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_24.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_24.setDecimals(1)
        self.doubleSpinBox_24.setMaximum(999.0)
        self.doubleSpinBox_24.setProperty("value", 0.0)
        self.doubleSpinBox_24.setObjectName("doubleSpinBox_24")
        self.verticalLayout_12.addWidget(self.doubleSpinBox_24)
        self.doubleSpinBox_25 = QtGui.QDoubleSpinBox(self.frame)
        self.doubleSpinBox_25.setWrapping(False)
        self.doubleSpinBox_25.setFrame(True)
        self.doubleSpinBox_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_25.setReadOnly(True)
        self.doubleSpinBox_25.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_25.setDecimals(1)
        self.doubleSpinBox_25.setMaximum(999.0)
        self.doubleSpinBox_25.setObjectName("doubleSpinBox_25")
        self.verticalLayout_12.addWidget(self.doubleSpinBox_25)
        self.horizontalLayout_7.addLayout(self.verticalLayout_12)
        self.gridLayout_14.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem4, 2, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.frame)
        self.frame_5 = QtGui.QFrame(self.tabGeneral1)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_16 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_46 = QtGui.QLabel(self.frame_5)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_18.addWidget(self.label_46)
        self.label_42 = QtGui.QLabel(self.frame_5)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_18.addWidget(self.label_42)
        self.label_41 = QtGui.QLabel(self.frame_5)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_18.addWidget(self.label_41)
        self.label_44 = QtGui.QLabel(self.frame_5)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_18.addWidget(self.label_44)
        self.label_45 = QtGui.QLabel(self.frame_5)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_18.addWidget(self.label_45)
        self.horizontalLayout_9.addLayout(self.verticalLayout_18)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.timeEdit = QtGui.QTimeEdit(self.frame_5)
        self.timeEdit.setObjectName("timeEdit")
        self.verticalLayout_16.addWidget(self.timeEdit)
        self.spinBox_4 = QtGui.QSpinBox(self.frame_5)
        self.spinBox_4.setObjectName("spinBox_4")
        self.verticalLayout_16.addWidget(self.spinBox_4)
        self.spinBox_3 = QtGui.QSpinBox(self.frame_5)
        self.spinBox_3.setObjectName("spinBox_3")
        self.verticalLayout_16.addWidget(self.spinBox_3)
        self.spinBox = QtGui.QSpinBox(self.frame_5)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_16.addWidget(self.spinBox)
        self.spinBox_2 = QtGui.QSpinBox(self.frame_5)
        self.spinBox_2.setObjectName("spinBox_2")
        self.verticalLayout_16.addWidget(self.spinBox_2)
        self.horizontalLayout_9.addLayout(self.verticalLayout_16)
        self.gridLayout_16.addLayout(self.horizontalLayout_9, 2, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem5, 3, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_16.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.frame_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_2 = QtGui.QFrame(self.tabGeneral1)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_8 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.label_11 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setUnderline(False)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox.setReadOnly(True)
        self.doubleSpinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox.setPrefix("")
        self.doubleSpinBox.setDecimals(1)
        self.doubleSpinBox.setMaximum(100.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.verticalLayout_6.addWidget(self.doubleSpinBox)
        self.label_12 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_6.addWidget(self.label_12)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBox_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_2.setReadOnly(True)
        self.doubleSpinBox_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_2.setDecimals(1)
        self.doubleSpinBox_2.setMaximum(500.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.verticalLayout_6.addWidget(self.doubleSpinBox_2)
        self.label_13 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_6.addWidget(self.label_13)
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBox_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_3.setReadOnly(True)
        self.doubleSpinBox_3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_3.setDecimals(1)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.verticalLayout_6.addWidget(self.doubleSpinBox_3)
        self.label_14 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_6.addWidget(self.label_14)
        self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBox_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_4.setReadOnly(True)
        self.doubleSpinBox_4.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_4.setDecimals(1)
        self.doubleSpinBox_4.setMaximum(100000.0)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.verticalLayout_6.addWidget(self.doubleSpinBox_4)
        self.gridLayout_8.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.frame_3 = QtGui.QFrame(self.tabGeneral1)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_10 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.label_15 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_8.addWidget(self.label_15)
        self.doubleSpinBox_9 = QtGui.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBox_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_9.setReadOnly(True)
        self.doubleSpinBox_9.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_9.setDecimals(1)
        self.doubleSpinBox_9.setMaximum(10000.0)
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.verticalLayout_8.addWidget(self.doubleSpinBox_9)
        self.label_20 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_8.addWidget(self.label_20)
        self.doubleSpinBox_10 = QtGui.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBox_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_10.setReadOnly(True)
        self.doubleSpinBox_10.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_10.setDecimals(1)
        self.doubleSpinBox_10.setObjectName("doubleSpinBox_10")
        self.verticalLayout_8.addWidget(self.doubleSpinBox_10)
        self.label_21 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_8.addWidget(self.label_21)
        self.doubleSpinBox_11 = QtGui.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBox_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_11.setReadOnly(True)
        self.doubleSpinBox_11.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_11.setDecimals(1)
        self.doubleSpinBox_11.setMaximum(1000.0)
        self.doubleSpinBox_11.setObjectName("doubleSpinBox_11")
        self.verticalLayout_8.addWidget(self.doubleSpinBox_11)
        self.label_22 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_8.addWidget(self.label_22)
        self.doubleSpinBox_12 = QtGui.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBox_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_12.setReadOnly(True)
        self.doubleSpinBox_12.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_12.setMaximum(1000.0)
        self.doubleSpinBox_12.setObjectName("doubleSpinBox_12")
        self.verticalLayout_8.addWidget(self.doubleSpinBox_12)
        self.gridLayout_10.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.frame_4 = QtGui.QFrame(self.tabGeneral1)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_12 = QtGui.QGridLayout(self.frame_4)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_5 = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_10.addWidget(self.label_5)
        self.label_27 = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_10.addWidget(self.label_27)
        self.doubleSpinBox_17 = QtGui.QDoubleSpinBox(self.frame_4)
        self.doubleSpinBox_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_17.setReadOnly(True)
        self.doubleSpinBox_17.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_17.setDecimals(1)
        self.doubleSpinBox_17.setMaximum(100000.0)
        self.doubleSpinBox_17.setObjectName("doubleSpinBox_17")
        self.verticalLayout_10.addWidget(self.doubleSpinBox_17)
        self.label_28 = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_10.addWidget(self.label_28)
        self.doubleSpinBox_18 = QtGui.QDoubleSpinBox(self.frame_4)
        self.doubleSpinBox_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_18.setReadOnly(True)
        self.doubleSpinBox_18.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_18.setDecimals(1)
        self.doubleSpinBox_18.setMaximum(1000.0)
        self.doubleSpinBox_18.setObjectName("doubleSpinBox_18")
        self.verticalLayout_10.addWidget(self.doubleSpinBox_18)
        self.label_29 = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_10.addWidget(self.label_29)
        self.spinBox_19 = QtGui.QSpinBox(self.frame_4)
        self.spinBox_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_19.setReadOnly(True)
        self.spinBox_19.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_19.setObjectName("spinBox_19")
        self.verticalLayout_10.addWidget(self.spinBox_19)
        self.label_30 = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_10.addWidget(self.label_30)
        self.doubleSpinBox_20 = QtGui.QDoubleSpinBox(self.frame_4)
        self.doubleSpinBox_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_20.setReadOnly(True)
        self.doubleSpinBox_20.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_20.setDecimals(1)
        self.doubleSpinBox_20.setObjectName("doubleSpinBox_20")
        self.verticalLayout_10.addWidget(self.doubleSpinBox_20)
        self.gridLayout_12.addLayout(self.verticalLayout_10, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.gridLayout_6.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.tab1.addTab(self.tabGeneral1, "")
        self.tabDetalle1 = QtGui.QWidget()
        self.tabDetalle1.setObjectName("tabDetalle1")
        self.gridLayout_2 = QtGui.QGridLayout(self.tabDetalle1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget_3 = QtGui.QTabWidget(self.tabDetalle1)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tabMotores1 = QtGui.QWidget()
        self.tabMotores1.setObjectName("tabMotores1")
        self.tabWidget_3.addTab(self.tabMotores1, "")
        self.tabBaterias1 = QtGui.QWidget()
        self.tabBaterias1.setObjectName("tabBaterias1")
        self.tabWidget_3.addTab(self.tabBaterias1, "")
        self.tabCeldas1 = QtGui.QWidget()
        self.tabCeldas1.setObjectName("tabCeldas1")
        self.tabWidget_3.addTab(self.tabCeldas1, "")
        self.gridLayout_2.addWidget(self.tabWidget_3, 0, 0, 1, 1)
        self.tab1.addTab(self.tabDetalle1, "")
        self.tabGraficos1 = QtGui.QWidget()
        self.tabGraficos1.setObjectName("tabGraficos1")
        self.gridLayout_4 = QtGui.QGridLayout(self.tabGraficos1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtGui.QWidget(self.tabGraficos1)
        self.widget.setObjectName("widget")
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_2 = QtGui.QWidget(self.tabGraficos1)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtGui.QWidget(self.tabGraficos1)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2.addWidget(self.widget_3)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tab1.addTab(self.tabGraficos1, "")
        self.tabHistorico1 = QtGui.QWidget()
        self.tabHistorico1.setObjectName("tabHistorico1")
        self.tab1.addTab(self.tabHistorico1, "")
        self.tabBitacora1 = QtGui.QWidget()
        self.tabBitacora1.setObjectName("tabBitacora1")
        self.tab1.addTab(self.tabBitacora1, "")
        self.horizontalLayout.addWidget(self.tab1)
        self.tab2 = QtGui.QTabWidget(self.centralwidget)
        self.tab2.setObjectName("tab2")
        self.tabGeneral2 = QtGui.QWidget()
        self.tabGeneral2.setObjectName("tabGeneral2")
        self.gridLayout_7 = QtGui.QGridLayout(self.tabGeneral2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_6 = QtGui.QFrame(self.tabGeneral2)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_15 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_38 = QtGui.QLabel(self.frame_6)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_14.addWidget(self.label_38)
        self.label_39 = QtGui.QLabel(self.frame_6)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_14.addWidget(self.label_39)
        self.label_40 = QtGui.QLabel(self.frame_6)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_14.addWidget(self.label_40)
        self.horizontalLayout_8.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.doubleSpinBox_26 = QtGui.QDoubleSpinBox(self.frame_6)
        self.doubleSpinBox_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_26.setReadOnly(True)
        self.doubleSpinBox_26.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_26.setSpecialValueText("")
        self.doubleSpinBox_26.setDecimals(1)
        self.doubleSpinBox_26.setMaximum(999.0)
        self.doubleSpinBox_26.setObjectName("doubleSpinBox_26")
        self.verticalLayout_15.addWidget(self.doubleSpinBox_26)
        self.doubleSpinBox_27 = QtGui.QDoubleSpinBox(self.frame_6)
        self.doubleSpinBox_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_27.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_27.setDecimals(1)
        self.doubleSpinBox_27.setMaximum(999.0)
        self.doubleSpinBox_27.setProperty("value", 0.0)
        self.doubleSpinBox_27.setObjectName("doubleSpinBox_27")
        self.verticalLayout_15.addWidget(self.doubleSpinBox_27)
        self.doubleSpinBox_28 = QtGui.QDoubleSpinBox(self.frame_6)
        self.doubleSpinBox_28.setWrapping(False)
        self.doubleSpinBox_28.setFrame(True)
        self.doubleSpinBox_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_28.setReadOnly(True)
        self.doubleSpinBox_28.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_28.setDecimals(1)
        self.doubleSpinBox_28.setMaximum(999.0)
        self.doubleSpinBox_28.setObjectName("doubleSpinBox_28")
        self.verticalLayout_15.addWidget(self.doubleSpinBox_28)
        self.horizontalLayout_8.addLayout(self.verticalLayout_15)
        self.gridLayout_15.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_15.addWidget(self.label_6, 0, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem6, 3, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.frame_6)
        self.frame_7 = QtGui.QFrame(self.tabGeneral2)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_17 = QtGui.QGridLayout(self.frame_7)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_7 = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_17.addWidget(self.label_7, 0, 0, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_59 = QtGui.QLabel(self.frame_7)
        self.label_59.setObjectName("label_59")
        self.verticalLayout_21.addWidget(self.label_59)
        self.label_60 = QtGui.QLabel(self.frame_7)
        self.label_60.setObjectName("label_60")
        self.verticalLayout_21.addWidget(self.label_60)
        self.label_61 = QtGui.QLabel(self.frame_7)
        self.label_61.setObjectName("label_61")
        self.verticalLayout_21.addWidget(self.label_61)
        self.label_62 = QtGui.QLabel(self.frame_7)
        self.label_62.setObjectName("label_62")
        self.verticalLayout_21.addWidget(self.label_62)
        self.label_63 = QtGui.QLabel(self.frame_7)
        self.label_63.setObjectName("label_63")
        self.verticalLayout_21.addWidget(self.label_63)
        self.horizontalLayout_11.addLayout(self.verticalLayout_21)
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.timeEdit_5 = QtGui.QTimeEdit(self.frame_7)
        self.timeEdit_5.setObjectName("timeEdit_5")
        self.verticalLayout_22.addWidget(self.timeEdit_5)
        self.spinBox_14 = QtGui.QSpinBox(self.frame_7)
        self.spinBox_14.setObjectName("spinBox_14")
        self.verticalLayout_22.addWidget(self.spinBox_14)
        self.spinBox_15 = QtGui.QSpinBox(self.frame_7)
        self.spinBox_15.setObjectName("spinBox_15")
        self.verticalLayout_22.addWidget(self.spinBox_15)
        self.spinBox_16 = QtGui.QSpinBox(self.frame_7)
        self.spinBox_16.setObjectName("spinBox_16")
        self.verticalLayout_22.addWidget(self.spinBox_16)
        self.spinBox_17 = QtGui.QSpinBox(self.frame_7)
        self.spinBox_17.setObjectName("spinBox_17")
        self.verticalLayout_22.addWidget(self.spinBox_17)
        self.horizontalLayout_11.addLayout(self.verticalLayout_22)
        self.gridLayout_17.addLayout(self.horizontalLayout_11, 1, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem7, 2, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.frame_7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_8 = QtGui.QFrame(self.tabGeneral2)
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_9 = QtGui.QGridLayout(self.frame_8)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_8 = QtGui.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.label_16 = QtGui.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setUnderline(False)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_7.addWidget(self.label_16)
        self.doubleSpinBox_5 = QtGui.QDoubleSpinBox(self.frame_8)
        self.doubleSpinBox_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_5.setReadOnly(True)
        self.doubleSpinBox_5.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_5.setPrefix("")
        self.doubleSpinBox_5.setDecimals(1)
        self.doubleSpinBox_5.setMaximum(100.0)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.verticalLayout_7.addWidget(self.doubleSpinBox_5)
        self.label_17 = QtGui.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_7.addWidget(self.label_17)
        self.doubleSpinBox_6 = QtGui.QDoubleSpinBox(self.frame_8)
        self.doubleSpinBox_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_6.setReadOnly(True)
        self.doubleSpinBox_6.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_6.setDecimals(1)
        self.doubleSpinBox_6.setMaximum(500.0)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.verticalLayout_7.addWidget(self.doubleSpinBox_6)
        self.label_18 = QtGui.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_7.addWidget(self.label_18)
        self.doubleSpinBox_7 = QtGui.QDoubleSpinBox(self.frame_8)
        self.doubleSpinBox_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_7.setReadOnly(True)
        self.doubleSpinBox_7.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_7.setDecimals(1)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.verticalLayout_7.addWidget(self.doubleSpinBox_7)
        self.label_19 = QtGui.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_7.addWidget(self.label_19)
        self.doubleSpinBox_8 = QtGui.QDoubleSpinBox(self.frame_8)
        self.doubleSpinBox_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_8.setReadOnly(True)
        self.doubleSpinBox_8.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_8.setDecimals(1)
        self.doubleSpinBox_8.setMaximum(100000.0)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.verticalLayout_7.addWidget(self.doubleSpinBox_8)
        self.gridLayout_9.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.frame_8)
        self.frame_9 = QtGui.QFrame(self.tabGeneral2)
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_11 = QtGui.QGridLayout(self.frame_9)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_9 = QtGui.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_9.addWidget(self.label_9)
        self.label_23 = QtGui.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_9.addWidget(self.label_23)
        self.doubleSpinBox_13 = QtGui.QDoubleSpinBox(self.frame_9)
        self.doubleSpinBox_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_13.setReadOnly(True)
        self.doubleSpinBox_13.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_13.setDecimals(1)
        self.doubleSpinBox_13.setMaximum(10000.0)
        self.doubleSpinBox_13.setObjectName("doubleSpinBox_13")
        self.verticalLayout_9.addWidget(self.doubleSpinBox_13)
        self.label_24 = QtGui.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_9.addWidget(self.label_24)
        self.doubleSpinBox_14 = QtGui.QDoubleSpinBox(self.frame_9)
        self.doubleSpinBox_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_14.setReadOnly(True)
        self.doubleSpinBox_14.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_14.setDecimals(1)
        self.doubleSpinBox_14.setObjectName("doubleSpinBox_14")
        self.verticalLayout_9.addWidget(self.doubleSpinBox_14)
        self.label_25 = QtGui.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_9.addWidget(self.label_25)
        self.doubleSpinBox_15 = QtGui.QDoubleSpinBox(self.frame_9)
        self.doubleSpinBox_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_15.setReadOnly(True)
        self.doubleSpinBox_15.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_15.setDecimals(1)
        self.doubleSpinBox_15.setMaximum(1000.0)
        self.doubleSpinBox_15.setObjectName("doubleSpinBox_15")
        self.verticalLayout_9.addWidget(self.doubleSpinBox_15)
        self.label_26 = QtGui.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_9.addWidget(self.label_26)
        self.doubleSpinBox_16 = QtGui.QDoubleSpinBox(self.frame_9)
        self.doubleSpinBox_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_16.setReadOnly(True)
        self.doubleSpinBox_16.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_16.setMaximum(1000.0)
        self.doubleSpinBox_16.setObjectName("doubleSpinBox_16")
        self.verticalLayout_9.addWidget(self.doubleSpinBox_16)
        self.gridLayout_11.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.frame_9)
        self.frame_10 = QtGui.QFrame(self.tabGeneral2)
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_13 = QtGui.QGridLayout(self.frame_10)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_10 = QtGui.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_11.addWidget(self.label_10)
        self.label_31 = QtGui.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_11.addWidget(self.label_31)
        self.doubleSpinBox_19 = QtGui.QDoubleSpinBox(self.frame_10)
        self.doubleSpinBox_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_19.setReadOnly(True)
        self.doubleSpinBox_19.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_19.setDecimals(1)
        self.doubleSpinBox_19.setMaximum(100000.0)
        self.doubleSpinBox_19.setObjectName("doubleSpinBox_19")
        self.verticalLayout_11.addWidget(self.doubleSpinBox_19)
        self.label_32 = QtGui.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_11.addWidget(self.label_32)
        self.doubleSpinBox_21 = QtGui.QDoubleSpinBox(self.frame_10)
        self.doubleSpinBox_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_21.setReadOnly(True)
        self.doubleSpinBox_21.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_21.setDecimals(1)
        self.doubleSpinBox_21.setMaximum(1000.0)
        self.doubleSpinBox_21.setObjectName("doubleSpinBox_21")
        self.verticalLayout_11.addWidget(self.doubleSpinBox_21)
        self.label_33 = QtGui.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_11.addWidget(self.label_33)
        self.spinBox_20 = QtGui.QSpinBox(self.frame_10)
        self.spinBox_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_20.setReadOnly(True)
        self.spinBox_20.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_20.setObjectName("spinBox_20")
        self.verticalLayout_11.addWidget(self.spinBox_20)
        self.label_34 = QtGui.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_11.addWidget(self.label_34)
        self.doubleSpinBox_22 = QtGui.QDoubleSpinBox(self.frame_10)
        self.doubleSpinBox_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_22.setReadOnly(True)
        self.doubleSpinBox_22.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_22.setDecimals(1)
        self.doubleSpinBox_22.setObjectName("doubleSpinBox_22")
        self.verticalLayout_11.addWidget(self.doubleSpinBox_22)
        self.gridLayout_13.addLayout(self.verticalLayout_11, 0, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.frame_10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.gridLayout_7.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.tab2.addTab(self.tabGeneral2, "")
        self.tabDetalle2 = QtGui.QWidget()
        self.tabDetalle2.setObjectName("tabDetalle2")
        self.gridLayout_3 = QtGui.QGridLayout(self.tabDetalle2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget_4 = QtGui.QTabWidget(self.tabDetalle2)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tabMotores2 = QtGui.QWidget()
        self.tabMotores2.setObjectName("tabMotores2")
        self.tabWidget_4.addTab(self.tabMotores2, "")
        self.tabBaterias2 = QtGui.QWidget()
        self.tabBaterias2.setObjectName("tabBaterias2")
        self.tabWidget_4.addTab(self.tabBaterias2, "")
        self.tabCeldas2 = QtGui.QWidget()
        self.tabCeldas2.setObjectName("tabCeldas2")
        self.tabWidget_4.addTab(self.tabCeldas2, "")
        self.gridLayout_3.addWidget(self.tabWidget_4, 0, 0, 1, 1)
        self.tab2.addTab(self.tabDetalle2, "")
        self.tabGraficos2 = QtGui.QWidget()
        self.tabGraficos2.setObjectName("tabGraficos2")
        self.gridLayout_5 = QtGui.QGridLayout(self.tabGraficos2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_4 = QtGui.QWidget(self.tabGraficos2)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_3.addWidget(self.widget_4)
        self.widget_5 = QtGui.QWidget(self.tabGraficos2)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_3.addWidget(self.widget_5)
        self.widget_6 = QtGui.QWidget(self.tabGraficos2)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_3.addWidget(self.widget_6)
        self.gridLayout_5.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tab2.addTab(self.tabGraficos2, "")
        self.tabHistorico2 = QtGui.QWidget()
        self.tabHistorico2.setObjectName("tabHistorico2")
        self.tab2.addTab(self.tabHistorico2, "")
        self.tabBitacora2 = QtGui.QWidget()
        self.tabBitacora2.setObjectName("tabBitacora2")
        self.tab2.addTab(self.tabBitacora2, "")
        self.horizontalLayout.addWidget(self.tab2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 870, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab1.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tab2.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.conectarWifi.setText(QtGui.QApplication.translate("MainWindow", "Conectar Wi-Fi", None, QtGui.QApplication.UnicodeUTF8))
        self.conectarXBee.setText(QtGui.QApplication.translate("MainWindow", "Conectar X-Bee", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Velocidad", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("MainWindow", "Crono Act.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("MainWindow", "Actual", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("MainWindow", "Promedio", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("MainWindow", "15 min", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_23.setSuffix(QtGui.QApplication.translate("MainWindow", " km/h", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_24.setSuffix(QtGui.QApplication.translate("MainWindow", " km/h", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_25.setSuffix(QtGui.QApplication.translate("MainWindow", " km/h", None, QtGui.QApplication.UnicodeUTF8))
        self.label_46.setText(QtGui.QApplication.translate("MainWindow", "Crono Mod", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("MainWindow", "Vel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("MainWindow", "Vel prom", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("MainWindow", "E. Gastada", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("MainWindow", "E. Modelo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Estrategia", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Baterías", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "SOC", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox.setSuffix(QtGui.QApplication.translate("MainWindow", " %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Voltaje", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_2.setSuffix(QtGui.QApplication.translate("MainWindow", " V", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "T° Max", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_3.setSuffix(QtGui.QApplication.translate("MainWindow", " °C", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Potencia", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_4.setSuffix(QtGui.QApplication.translate("MainWindow", " W", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "P. Entrada", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Pot. Celdas", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_9.setSuffix(QtGui.QApplication.translate("MainWindow", " W", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("MainWindow", "Temp.", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_10.setSuffix(QtGui.QApplication.translate("MainWindow", " °C", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Voltaje", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_11.setSuffix(QtGui.QApplication.translate("MainWindow", " V", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("MainWindow", "Corriente", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_12.setSuffix(QtGui.QApplication.translate("MainWindow", " A", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "P. Salida", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Pot. Motor", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_17.setSuffix(QtGui.QApplication.translate("MainWindow", " W", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "T ° Max", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_18.setSuffix(QtGui.QApplication.translate("MainWindow", " °C", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "Activos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("MainWindow", "Eficiencia", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_20.setSuffix(QtGui.QApplication.translate("MainWindow", " %", None, QtGui.QApplication.UnicodeUTF8))
        self.tab1.setTabText(self.tab1.indexOf(self.tabGeneral1), QtGui.QApplication.translate("MainWindow", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tabMotores1), QtGui.QApplication.translate("MainWindow", "Motores", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tabBaterias1), QtGui.QApplication.translate("MainWindow", "Baterías", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tabCeldas1), QtGui.QApplication.translate("MainWindow", "Celdas", None, QtGui.QApplication.UnicodeUTF8))
        self.tab1.setTabText(self.tab1.indexOf(self.tabDetalle1), QtGui.QApplication.translate("MainWindow", "Detalle", None, QtGui.QApplication.UnicodeUTF8))
        self.tab1.setTabText(self.tab1.indexOf(self.tabGraficos1), QtGui.QApplication.translate("MainWindow", "Gráficos", None, QtGui.QApplication.UnicodeUTF8))
        self.tab1.setTabText(self.tab1.indexOf(self.tabHistorico1), QtGui.QApplication.translate("MainWindow", "Histórico", None, QtGui.QApplication.UnicodeUTF8))
        self.tab1.setTabText(self.tab1.indexOf(self.tabBitacora1), QtGui.QApplication.translate("MainWindow", "Bitácora", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("MainWindow", "Actual", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("MainWindow", "Promedio", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("MainWindow", "15 min", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_26.setSuffix(QtGui.QApplication.translate("MainWindow", " km/h", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_27.setSuffix(QtGui.QApplication.translate("MainWindow", " km/h", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_28.setSuffix(QtGui.QApplication.translate("MainWindow", " km/h", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Velocidad", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Estrategia", None, QtGui.QApplication.UnicodeUTF8))
        self.label_59.setText(QtGui.QApplication.translate("MainWindow", "Crono Mod", None, QtGui.QApplication.UnicodeUTF8))
        self.label_60.setText(QtGui.QApplication.translate("MainWindow", "Vel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_61.setText(QtGui.QApplication.translate("MainWindow", "Vel prom", None, QtGui.QApplication.UnicodeUTF8))
        self.label_62.setText(QtGui.QApplication.translate("MainWindow", "E. Gastada", None, QtGui.QApplication.UnicodeUTF8))
        self.label_63.setText(QtGui.QApplication.translate("MainWindow", "E. Modelo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Baterías", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "SOC", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_5.setSuffix(QtGui.QApplication.translate("MainWindow", " %", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Voltaje", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_6.setSuffix(QtGui.QApplication.translate("MainWindow", " V", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "T° Max", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_7.setSuffix(QtGui.QApplication.translate("MainWindow", " °C", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Potencia", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_8.setSuffix(QtGui.QApplication.translate("MainWindow", " W", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "P. Entrada", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Pot. Celdas", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_13.setSuffix(QtGui.QApplication.translate("MainWindow", " W", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Temp.", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_14.setSuffix(QtGui.QApplication.translate("MainWindow", " °C", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Voltaje", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_15.setSuffix(QtGui.QApplication.translate("MainWindow", " V", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Corriente", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_16.setSuffix(QtGui.QApplication.translate("MainWindow", " A", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "P. Salida", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("MainWindow", "Pot. Motor", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_19.setSuffix(QtGui.QApplication.translate("MainWindow", " W", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "T ° Max", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_21.setSuffix(QtGui.QApplication.translate("MainWindow", " °C", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("MainWindow", "Activos", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("MainWindow", "Eficiencia", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox_22.setSuffix(QtGui.QApplication.translate("MainWindow", " %", None, QtGui.QApplication.UnicodeUTF8))
        self.tab2.setTabText(self.tab2.indexOf(self.tabGeneral2), QtGui.QApplication.translate("MainWindow", "General", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tabMotores2), QtGui.QApplication.translate("MainWindow", "Motores", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tabBaterias2), QtGui.QApplication.translate("MainWindow", "Baterías", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tabCeldas2), QtGui.QApplication.translate("MainWindow", "Celdas", None, QtGui.QApplication.UnicodeUTF8))
        self.tab2.setTabText(self.tab2.indexOf(self.tabDetalle2), QtGui.QApplication.translate("MainWindow", "Detalle", None, QtGui.QApplication.UnicodeUTF8))
        self.tab2.setTabText(self.tab2.indexOf(self.tabGraficos2), QtGui.QApplication.translate("MainWindow", "Gráficos", None, QtGui.QApplication.UnicodeUTF8))
        self.tab2.setTabText(self.tab2.indexOf(self.tabHistorico2), QtGui.QApplication.translate("MainWindow", "Histórico", None, QtGui.QApplication.UnicodeUTF8))
        self.tab2.setTabText(self.tab2.indexOf(self.tabBitacora2), QtGui.QApplication.translate("MainWindow", "Bitácora", None, QtGui.QApplication.UnicodeUTF8))

