# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/rodrigo/telemetriafinal/telemetria/ui/disenos/designer/mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 653)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.conectarWifi = QtGui.QPushButton(self.centralwidget)
        self.conectarWifi.setObjectName(_fromUtf8("conectarWifi"))
        self.horizontalLayout_2.addWidget(self.conectarWifi)
        self.checkBoxWifi = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxWifi.setText(_fromUtf8(""))
        self.checkBoxWifi.setObjectName(_fromUtf8("checkBoxWifi"))
        self.horizontalLayout_2.addWidget(self.checkBoxWifi)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.conectarXBee = QtGui.QPushButton(self.centralwidget)
        self.conectarXBee.setObjectName(_fromUtf8("conectarXBee"))
        self.horizontalLayout_2.addWidget(self.conectarXBee)
        self.checkBoxXbee = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxXbee.setText(_fromUtf8(""))
        self.checkBoxXbee.setObjectName(_fromUtf8("checkBoxXbee"))
        self.horizontalLayout_2.addWidget(self.checkBoxXbee)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.fecha = QtGui.QDateTimeEdit(self.centralwidget)
        self.fecha.setAlignment(QtCore.Qt.AlignCenter)
        self.fecha.setReadOnly(True)
        self.fecha.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.fecha.setObjectName(_fromUtf8("fecha"))
        self.horizontalLayout_2.addWidget(self.fecha)
        self.label_47 = QtGui.QLabel(self.centralwidget)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.horizontalLayout_2.addWidget(self.label_47)
        self.hora_partida = QtGui.QTimeEdit(self.centralwidget)
        self.hora_partida.setAlignment(QtCore.Qt.AlignCenter)
        self.hora_partida.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.hora_partida.setObjectName(_fromUtf8("hora_partida"))
        self.horizontalLayout_2.addWidget(self.hora_partida)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.cargaBaterias = QtGui.QProgressBar(self.centralwidget)
        self.cargaBaterias.setProperty("value", 24)
        self.cargaBaterias.setObjectName(_fromUtf8("cargaBaterias"))
        self.horizontalLayout_2.addWidget(self.cargaBaterias)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tab1 = QtGui.QTabWidget(self.centralwidget)
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.tabGeneral1 = QtGui.QWidget()
        self.tabGeneral1.setObjectName(_fromUtf8("tabGeneral1"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tabGeneral1)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.frame = QtGui.QFrame(self.tabGeneral1)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_14 = QtGui.QGridLayout(self.frame)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.label = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_14.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_43 = QtGui.QLabel(self.frame)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.verticalLayout_13.addWidget(self.label_43)
        self.label_35 = QtGui.QLabel(self.frame)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.verticalLayout_13.addWidget(self.label_35)
        self.label_36 = QtGui.QLabel(self.frame)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.verticalLayout_13.addWidget(self.label_36)
        self.label_37 = QtGui.QLabel(self.frame)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.verticalLayout_13.addWidget(self.label_37)
        self.horizontalLayout_7.addLayout(self.verticalLayout_13)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.tiempo_crono_1 = QtGui.QTimeEdit(self.frame)
        self.tiempo_crono_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tiempo_crono_1.setReadOnly(True)
        self.tiempo_crono_1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.tiempo_crono_1.setObjectName(_fromUtf8("tiempo_crono_1"))
        self.verticalLayout_12.addWidget(self.tiempo_crono_1)
        self.vel_actual_1 = QtGui.QDoubleSpinBox(self.frame)
        self.vel_actual_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.vel_actual_1.setReadOnly(True)
        self.vel_actual_1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.vel_actual_1.setSpecialValueText(_fromUtf8(""))
        self.vel_actual_1.setDecimals(1)
        self.vel_actual_1.setMinimum(-300.0)
        self.vel_actual_1.setMaximum(300.0)
        self.vel_actual_1.setProperty("value", 0.0)
        self.vel_actual_1.setObjectName(_fromUtf8("vel_actual_1"))
        self.verticalLayout_12.addWidget(self.vel_actual_1)
        self.vel_prom_1 = QtGui.QDoubleSpinBox(self.frame)
        self.vel_prom_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.vel_prom_1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.vel_prom_1.setDecimals(1)
        self.vel_prom_1.setMinimum(-300.0)
        self.vel_prom_1.setMaximum(300.0)
        self.vel_prom_1.setProperty("value", 0.0)
        self.vel_prom_1.setObjectName(_fromUtf8("vel_prom_1"))
        self.verticalLayout_12.addWidget(self.vel_prom_1)
        self.vel_cuarto_1 = QtGui.QDoubleSpinBox(self.frame)
        self.vel_cuarto_1.setWrapping(False)
        self.vel_cuarto_1.setFrame(True)
        self.vel_cuarto_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.vel_cuarto_1.setReadOnly(True)
        self.vel_cuarto_1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.vel_cuarto_1.setDecimals(1)
        self.vel_cuarto_1.setMinimum(-300.0)
        self.vel_cuarto_1.setMaximum(300.0)
        self.vel_cuarto_1.setObjectName(_fromUtf8("vel_cuarto_1"))
        self.verticalLayout_12.addWidget(self.vel_cuarto_1)
        self.horizontalLayout_7.addLayout(self.verticalLayout_12)
        self.gridLayout_14.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem4, 2, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.frame)
        self.frame_5 = QtGui.QFrame(self.tabGeneral1)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout_16 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.label_46 = QtGui.QLabel(self.frame_5)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.verticalLayout_18.addWidget(self.label_46)
        self.label_42 = QtGui.QLabel(self.frame_5)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.verticalLayout_18.addWidget(self.label_42)
        self.label_41 = QtGui.QLabel(self.frame_5)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.verticalLayout_18.addWidget(self.label_41)
        self.label_44 = QtGui.QLabel(self.frame_5)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.verticalLayout_18.addWidget(self.label_44)
        self.label_45 = QtGui.QLabel(self.frame_5)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.verticalLayout_18.addWidget(self.label_45)
        self.horizontalLayout_9.addLayout(self.verticalLayout_18)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.timeEdit = QtGui.QTimeEdit(self.frame_5)
        self.timeEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeEdit.setReadOnly(True)
        self.timeEdit.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.timeEdit.setObjectName(_fromUtf8("timeEdit"))
        self.verticalLayout_16.addWidget(self.timeEdit)
        self.spinBox_4 = QtGui.QSpinBox(self.frame_5)
        self.spinBox_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_4.setReadOnly(True)
        self.spinBox_4.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.verticalLayout_16.addWidget(self.spinBox_4)
        self.spinBox_3 = QtGui.QSpinBox(self.frame_5)
        self.spinBox_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_3.setReadOnly(True)
        self.spinBox_3.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.verticalLayout_16.addWidget(self.spinBox_3)
        self.spinBox = QtGui.QSpinBox(self.frame_5)
        self.spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox.setReadOnly(True)
        self.spinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.verticalLayout_16.addWidget(self.spinBox)
        self.spinBox_2 = QtGui.QSpinBox(self.frame_5)
        self.spinBox_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_2.setReadOnly(True)
        self.spinBox_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.verticalLayout_16.addWidget(self.spinBox_2)
        self.horizontalLayout_9.addLayout(self.verticalLayout_16)
        self.gridLayout_16.addLayout(self.horizontalLayout_9, 2, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_16.addItem(spacerItem5, 3, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_16.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.frame_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.frame_2 = QtGui.QFrame(self.tabGeneral1)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_8 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_3 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_6.addWidget(self.label_3)
        self.label_11 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_6.addWidget(self.label_11)
        self.soc_1 = QtGui.QDoubleSpinBox(self.frame_2)
        self.soc_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.soc_1.setReadOnly(True)
        self.soc_1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.soc_1.setPrefix(_fromUtf8(""))
        self.soc_1.setDecimals(1)
        self.soc_1.setMaximum(100.0)
        self.soc_1.setObjectName(_fromUtf8("soc_1"))
        self.verticalLayout_6.addWidget(self.soc_1)
        self.label_12 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_6.addWidget(self.label_12)
        self.voltaje_1 = QtGui.QDoubleSpinBox(self.frame_2)
        self.voltaje_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.voltaje_1.setReadOnly(True)
        self.voltaje_1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.voltaje_1.setDecimals(1)
        self.voltaje_1.setMaximum(500.0)
        self.voltaje_1.setObjectName(_fromUtf8("voltaje_1"))
        self.verticalLayout_6.addWidget(self.voltaje_1)
        self.label_13 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_6.addWidget(self.label_13)
        self.T_max_baterias_1 = QtGui.QDoubleSpinBox(self.frame_2)
        self.T_max_baterias_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.T_max_baterias_1.setReadOnly(True)
        self.T_max_baterias_1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.T_max_baterias_1.setDecimals(1)
        self.T_max_baterias_1.setMaximum(300.0)
        self.T_max_baterias_1.setObjectName(_fromUtf8("T_max_baterias_1"))
        self.verticalLayout_6.addWidget(self.T_max_baterias_1)
        self.label_14 = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_6.addWidget(self.label_14)
        self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(self.frame_2)
        self.doubleSpinBox_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_4.setReadOnly(True)
        self.doubleSpinBox_4.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_4.setDecimals(1)
        self.doubleSpinBox_4.setMinimum(-100000.0)
        self.doubleSpinBox_4.setMaximum(100000.0)
        self.doubleSpinBox_4.setObjectName(_fromUtf8("doubleSpinBox_4"))
        self.verticalLayout_6.addWidget(self.doubleSpinBox_4)
        self.gridLayout_8.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.frame_3 = QtGui.QFrame(self.tabGeneral1)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_10 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_4 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_8.addWidget(self.label_4)
        self.label_15 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_8.addWidget(self.label_15)
        self.doubleSpinBox_9 = QtGui.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBox_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_9.setReadOnly(True)
        self.doubleSpinBox_9.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_9.setDecimals(1)
        self.doubleSpinBox_9.setMaximum(10000.0)
        self.doubleSpinBox_9.setObjectName(_fromUtf8("doubleSpinBox_9"))
        self.verticalLayout_8.addWidget(self.doubleSpinBox_9)
        self.label_20 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_8.addWidget(self.label_20)
        self.doubleSpinBox_10 = QtGui.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBox_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_10.setReadOnly(True)
        self.doubleSpinBox_10.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_10.setDecimals(1)
        self.doubleSpinBox_10.setObjectName(_fromUtf8("doubleSpinBox_10"))
        self.verticalLayout_8.addWidget(self.doubleSpinBox_10)
        self.label_21 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_8.addWidget(self.label_21)
        self.doubleSpinBox_11 = QtGui.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBox_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_11.setReadOnly(True)
        self.doubleSpinBox_11.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_11.setDecimals(1)
        self.doubleSpinBox_11.setMaximum(1000.0)
        self.doubleSpinBox_11.setObjectName(_fromUtf8("doubleSpinBox_11"))
        self.verticalLayout_8.addWidget(self.doubleSpinBox_11)
        self.label_22 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_8.addWidget(self.label_22)
        self.doubleSpinBox_12 = QtGui.QDoubleSpinBox(self.frame_3)
        self.doubleSpinBox_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_12.setReadOnly(True)
        self.doubleSpinBox_12.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_12.setMaximum(1000.0)
        self.doubleSpinBox_12.setObjectName(_fromUtf8("doubleSpinBox_12"))
        self.verticalLayout_8.addWidget(self.doubleSpinBox_12)
        self.gridLayout_10.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.frame_4 = QtGui.QFrame(self.tabGeneral1)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.gridLayout_12 = QtGui.QGridLayout(self.frame_4)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_5 = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_10.addWidget(self.label_5)
        self.label_27 = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.verticalLayout_10.addWidget(self.label_27)
        self.potencia_motores_1 = QtGui.QDoubleSpinBox(self.frame_4)
        self.potencia_motores_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.potencia_motores_1.setReadOnly(True)
        self.potencia_motores_1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.potencia_motores_1.setDecimals(1)
        self.potencia_motores_1.setMaximum(100000.0)
        self.potencia_motores_1.setObjectName(_fromUtf8("potencia_motores_1"))
        self.verticalLayout_10.addWidget(self.potencia_motores_1)
        self.label_28 = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.verticalLayout_10.addWidget(self.label_28)
        self.T_max_motores_1 = QtGui.QDoubleSpinBox(self.frame_4)
        self.T_max_motores_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.T_max_motores_1.setReadOnly(True)
        self.T_max_motores_1.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.T_max_motores_1.setDecimals(1)
        self.T_max_motores_1.setMaximum(1000.0)
        self.T_max_motores_1.setObjectName(_fromUtf8("T_max_motores_1"))
        self.verticalLayout_10.addWidget(self.T_max_motores_1)
        self.label_29 = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.verticalLayout_10.addWidget(self.label_29)
        self.spinBox_19 = QtGui.QSpinBox(self.frame_4)
        self.spinBox_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_19.setReadOnly(True)
        self.spinBox_19.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_19.setObjectName(_fromUtf8("spinBox_19"))
        self.verticalLayout_10.addWidget(self.spinBox_19)
        self.label_30 = QtGui.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.verticalLayout_10.addWidget(self.label_30)
        self.doubleSpinBox_20 = QtGui.QDoubleSpinBox(self.frame_4)
        self.doubleSpinBox_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_20.setReadOnly(True)
        self.doubleSpinBox_20.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_20.setDecimals(1)
        self.doubleSpinBox_20.setObjectName(_fromUtf8("doubleSpinBox_20"))
        self.verticalLayout_10.addWidget(self.doubleSpinBox_20)
        self.gridLayout_12.addLayout(self.verticalLayout_10, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.gridLayout_6.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.tab1.addTab(self.tabGeneral1, _fromUtf8(""))
        self.tabDetalle1 = QtGui.QWidget()
        self.tabDetalle1.setObjectName(_fromUtf8("tabDetalle1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tabDetalle1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidget_3 = QtGui.QTabWidget(self.tabDetalle1)
        self.tabWidget_3.setObjectName(_fromUtf8("tabWidget_3"))
        self.tabMotores1 = QtGui.QWidget()
        self.tabMotores1.setObjectName(_fromUtf8("tabMotores1"))
        self.tabWidget_3.addTab(self.tabMotores1, _fromUtf8(""))
        self.tabBaterias1 = QtGui.QWidget()
        self.tabBaterias1.setObjectName(_fromUtf8("tabBaterias1"))
        self.tabWidget_3.addTab(self.tabBaterias1, _fromUtf8(""))
        self.tabCeldas1 = QtGui.QWidget()
        self.tabCeldas1.setObjectName(_fromUtf8("tabCeldas1"))
        self.tabWidget_3.addTab(self.tabCeldas1, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget_3, 0, 0, 1, 1)
        self.tab1.addTab(self.tabDetalle1, _fromUtf8(""))
        self.tabGraficos1 = QtGui.QWidget()
        self.tabGraficos1.setObjectName(_fromUtf8("tabGraficos1"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tabGraficos1)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.graphicsView = QtGui.QGraphicsView(self.tabGraficos1)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayout_2.addWidget(self.graphicsView)
        self.graphicsView_2 = QtGui.QGraphicsView(self.tabGraficos1)
        self.graphicsView_2.setObjectName(_fromUtf8("graphicsView_2"))
        self.verticalLayout_2.addWidget(self.graphicsView_2)
        self.graphicsView_3 = QtGui.QGraphicsView(self.tabGraficos1)
        self.graphicsView_3.setObjectName(_fromUtf8("graphicsView_3"))
        self.verticalLayout_2.addWidget(self.graphicsView_3)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tab1.addTab(self.tabGraficos1, _fromUtf8(""))
        self.tabHistorico1 = QtGui.QWidget()
        self.tabHistorico1.setObjectName(_fromUtf8("tabHistorico1"))
        self.tab1.addTab(self.tabHistorico1, _fromUtf8(""))
        self.tabBitacora1 = QtGui.QWidget()
        self.tabBitacora1.setObjectName(_fromUtf8("tabBitacora1"))
        self.tab1.addTab(self.tabBitacora1, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tab1)
        self.tab2 = QtGui.QTabWidget(self.centralwidget)
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.tabGeneral2 = QtGui.QWidget()
        self.tabGeneral2.setObjectName(_fromUtf8("tabGeneral2"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tabGeneral2)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.frame_6 = QtGui.QFrame(self.tabGeneral2)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.gridLayout_15 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_64 = QtGui.QLabel(self.frame_6)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.verticalLayout_14.addWidget(self.label_64)
        self.label_38 = QtGui.QLabel(self.frame_6)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.verticalLayout_14.addWidget(self.label_38)
        self.label_39 = QtGui.QLabel(self.frame_6)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.verticalLayout_14.addWidget(self.label_39)
        self.label_40 = QtGui.QLabel(self.frame_6)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.verticalLayout_14.addWidget(self.label_40)
        self.horizontalLayout_8.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.tiempo_crono_2 = QtGui.QTimeEdit(self.frame_6)
        self.tiempo_crono_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tiempo_crono_2.setReadOnly(True)
        self.tiempo_crono_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.tiempo_crono_2.setObjectName(_fromUtf8("tiempo_crono_2"))
        self.verticalLayout_15.addWidget(self.tiempo_crono_2)
        self.vel_actual_2 = QtGui.QDoubleSpinBox(self.frame_6)
        self.vel_actual_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.vel_actual_2.setReadOnly(True)
        self.vel_actual_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.vel_actual_2.setSpecialValueText(_fromUtf8(""))
        self.vel_actual_2.setDecimals(1)
        self.vel_actual_2.setMinimum(-300.0)
        self.vel_actual_2.setMaximum(300.0)
        self.vel_actual_2.setObjectName(_fromUtf8("vel_actual_2"))
        self.verticalLayout_15.addWidget(self.vel_actual_2)
        self.vel_prom_2 = QtGui.QDoubleSpinBox(self.frame_6)
        self.vel_prom_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.vel_prom_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.vel_prom_2.setDecimals(1)
        self.vel_prom_2.setMinimum(-300.0)
        self.vel_prom_2.setMaximum(300.0)
        self.vel_prom_2.setProperty("value", 0.0)
        self.vel_prom_2.setObjectName(_fromUtf8("vel_prom_2"))
        self.verticalLayout_15.addWidget(self.vel_prom_2)
        self.vel_cuarto_2 = QtGui.QDoubleSpinBox(self.frame_6)
        self.vel_cuarto_2.setWrapping(False)
        self.vel_cuarto_2.setFrame(True)
        self.vel_cuarto_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.vel_cuarto_2.setReadOnly(True)
        self.vel_cuarto_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.vel_cuarto_2.setDecimals(1)
        self.vel_cuarto_2.setMinimum(-300.0)
        self.vel_cuarto_2.setMaximum(300.0)
        self.vel_cuarto_2.setObjectName(_fromUtf8("vel_cuarto_2"))
        self.verticalLayout_15.addWidget(self.vel_cuarto_2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_15)
        self.gridLayout_15.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_15.addWidget(self.label_6, 0, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem6, 3, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.frame_6)
        self.frame_7 = QtGui.QFrame(self.tabGeneral2)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.gridLayout_17 = QtGui.QGridLayout(self.frame_7)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.label_7 = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_17.addWidget(self.label_7, 0, 0, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.label_59 = QtGui.QLabel(self.frame_7)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.verticalLayout_21.addWidget(self.label_59)
        self.label_60 = QtGui.QLabel(self.frame_7)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.verticalLayout_21.addWidget(self.label_60)
        self.label_61 = QtGui.QLabel(self.frame_7)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.verticalLayout_21.addWidget(self.label_61)
        self.label_62 = QtGui.QLabel(self.frame_7)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.verticalLayout_21.addWidget(self.label_62)
        self.label_63 = QtGui.QLabel(self.frame_7)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.verticalLayout_21.addWidget(self.label_63)
        self.horizontalLayout_11.addLayout(self.verticalLayout_21)
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.spinBox_17 = QtGui.QSpinBox(self.frame_7)
        self.spinBox_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_17.setReadOnly(True)
        self.spinBox_17.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_17.setObjectName(_fromUtf8("spinBox_17"))
        self.verticalLayout_22.addWidget(self.spinBox_17)
        self.spinBox_16 = QtGui.QSpinBox(self.frame_7)
        self.spinBox_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_16.setReadOnly(True)
        self.spinBox_16.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_16.setObjectName(_fromUtf8("spinBox_16"))
        self.verticalLayout_22.addWidget(self.spinBox_16)
        self.spinBox_15 = QtGui.QSpinBox(self.frame_7)
        self.spinBox_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_15.setReadOnly(True)
        self.spinBox_15.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_15.setObjectName(_fromUtf8("spinBox_15"))
        self.verticalLayout_22.addWidget(self.spinBox_15)
        self.timeEdit_5 = QtGui.QTimeEdit(self.frame_7)
        self.timeEdit_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeEdit_5.setReadOnly(True)
        self.timeEdit_5.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.timeEdit_5.setObjectName(_fromUtf8("timeEdit_5"))
        self.verticalLayout_22.addWidget(self.timeEdit_5)
        self.spinBox_14 = QtGui.QSpinBox(self.frame_7)
        self.spinBox_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_14.setReadOnly(True)
        self.spinBox_14.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_14.setObjectName(_fromUtf8("spinBox_14"))
        self.verticalLayout_22.addWidget(self.spinBox_14)
        self.horizontalLayout_11.addLayout(self.verticalLayout_22)
        self.gridLayout_17.addLayout(self.horizontalLayout_11, 1, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_17.addItem(spacerItem7, 2, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.frame_7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.frame_8 = QtGui.QFrame(self.tabGeneral2)
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.gridLayout_9 = QtGui.QGridLayout(self.frame_8)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_8 = QtGui.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_7.addWidget(self.label_8)
        self.label_16 = QtGui.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_7.addWidget(self.label_16)
        self.soc_2 = QtGui.QDoubleSpinBox(self.frame_8)
        self.soc_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.soc_2.setReadOnly(True)
        self.soc_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.soc_2.setPrefix(_fromUtf8(""))
        self.soc_2.setDecimals(1)
        self.soc_2.setMaximum(100.0)
        self.soc_2.setObjectName(_fromUtf8("soc_2"))
        self.verticalLayout_7.addWidget(self.soc_2)
        self.label_17 = QtGui.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_7.addWidget(self.label_17)
        self.voltaje_2 = QtGui.QDoubleSpinBox(self.frame_8)
        self.voltaje_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.voltaje_2.setReadOnly(True)
        self.voltaje_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.voltaje_2.setDecimals(1)
        self.voltaje_2.setMaximum(500.0)
        self.voltaje_2.setObjectName(_fromUtf8("voltaje_2"))
        self.verticalLayout_7.addWidget(self.voltaje_2)
        self.label_18 = QtGui.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_7.addWidget(self.label_18)
        self.T_max_baterias_2 = QtGui.QDoubleSpinBox(self.frame_8)
        self.T_max_baterias_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.T_max_baterias_2.setReadOnly(True)
        self.T_max_baterias_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.T_max_baterias_2.setDecimals(1)
        self.T_max_baterias_2.setMaximum(300.0)
        self.T_max_baterias_2.setObjectName(_fromUtf8("T_max_baterias_2"))
        self.verticalLayout_7.addWidget(self.T_max_baterias_2)
        self.label_19 = QtGui.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_7.addWidget(self.label_19)
        self.doubleSpinBox_8 = QtGui.QDoubleSpinBox(self.frame_8)
        self.doubleSpinBox_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_8.setReadOnly(True)
        self.doubleSpinBox_8.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_8.setDecimals(1)
        self.doubleSpinBox_8.setMinimum(-100000.0)
        self.doubleSpinBox_8.setMaximum(100000.0)
        self.doubleSpinBox_8.setObjectName(_fromUtf8("doubleSpinBox_8"))
        self.verticalLayout_7.addWidget(self.doubleSpinBox_8)
        self.gridLayout_9.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.frame_8)
        self.frame_9 = QtGui.QFrame(self.tabGeneral2)
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.gridLayout_11 = QtGui.QGridLayout(self.frame_9)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_9 = QtGui.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_9.addWidget(self.label_9)
        self.label_23 = QtGui.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_9.addWidget(self.label_23)
        self.doubleSpinBox_13 = QtGui.QDoubleSpinBox(self.frame_9)
        self.doubleSpinBox_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_13.setReadOnly(True)
        self.doubleSpinBox_13.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_13.setDecimals(1)
        self.doubleSpinBox_13.setMaximum(10000.0)
        self.doubleSpinBox_13.setObjectName(_fromUtf8("doubleSpinBox_13"))
        self.verticalLayout_9.addWidget(self.doubleSpinBox_13)
        self.label_24 = QtGui.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.verticalLayout_9.addWidget(self.label_24)
        self.doubleSpinBox_14 = QtGui.QDoubleSpinBox(self.frame_9)
        self.doubleSpinBox_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_14.setReadOnly(True)
        self.doubleSpinBox_14.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_14.setDecimals(1)
        self.doubleSpinBox_14.setObjectName(_fromUtf8("doubleSpinBox_14"))
        self.verticalLayout_9.addWidget(self.doubleSpinBox_14)
        self.label_25 = QtGui.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.verticalLayout_9.addWidget(self.label_25)
        self.doubleSpinBox_15 = QtGui.QDoubleSpinBox(self.frame_9)
        self.doubleSpinBox_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_15.setReadOnly(True)
        self.doubleSpinBox_15.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_15.setDecimals(1)
        self.doubleSpinBox_15.setMaximum(1000.0)
        self.doubleSpinBox_15.setObjectName(_fromUtf8("doubleSpinBox_15"))
        self.verticalLayout_9.addWidget(self.doubleSpinBox_15)
        self.label_26 = QtGui.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.verticalLayout_9.addWidget(self.label_26)
        self.doubleSpinBox_16 = QtGui.QDoubleSpinBox(self.frame_9)
        self.doubleSpinBox_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_16.setReadOnly(True)
        self.doubleSpinBox_16.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_16.setMaximum(1000.0)
        self.doubleSpinBox_16.setObjectName(_fromUtf8("doubleSpinBox_16"))
        self.verticalLayout_9.addWidget(self.doubleSpinBox_16)
        self.gridLayout_11.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.frame_9)
        self.frame_10 = QtGui.QFrame(self.tabGeneral2)
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.gridLayout_13 = QtGui.QGridLayout(self.frame_10)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_10 = QtGui.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_11.addWidget(self.label_10)
        self.label_31 = QtGui.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.verticalLayout_11.addWidget(self.label_31)
        self.potencia_motores_2 = QtGui.QDoubleSpinBox(self.frame_10)
        self.potencia_motores_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.potencia_motores_2.setReadOnly(True)
        self.potencia_motores_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.potencia_motores_2.setDecimals(1)
        self.potencia_motores_2.setMaximum(100000.0)
        self.potencia_motores_2.setObjectName(_fromUtf8("potencia_motores_2"))
        self.verticalLayout_11.addWidget(self.potencia_motores_2)
        self.label_32 = QtGui.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.verticalLayout_11.addWidget(self.label_32)
        self.T_max_motores_2 = QtGui.QDoubleSpinBox(self.frame_10)
        self.T_max_motores_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.T_max_motores_2.setReadOnly(True)
        self.T_max_motores_2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.T_max_motores_2.setDecimals(1)
        self.T_max_motores_2.setMaximum(1000.0)
        self.T_max_motores_2.setObjectName(_fromUtf8("T_max_motores_2"))
        self.verticalLayout_11.addWidget(self.T_max_motores_2)
        self.label_33 = QtGui.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.verticalLayout_11.addWidget(self.label_33)
        self.spinBox_20 = QtGui.QSpinBox(self.frame_10)
        self.spinBox_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_20.setReadOnly(True)
        self.spinBox_20.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBox_20.setObjectName(_fromUtf8("spinBox_20"))
        self.verticalLayout_11.addWidget(self.spinBox_20)
        self.label_34 = QtGui.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.verticalLayout_11.addWidget(self.label_34)
        self.doubleSpinBox_22 = QtGui.QDoubleSpinBox(self.frame_10)
        self.doubleSpinBox_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_22.setReadOnly(True)
        self.doubleSpinBox_22.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBox_22.setDecimals(1)
        self.doubleSpinBox_22.setObjectName(_fromUtf8("doubleSpinBox_22"))
        self.verticalLayout_11.addWidget(self.doubleSpinBox_22)
        self.gridLayout_13.addLayout(self.verticalLayout_11, 0, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.frame_10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.gridLayout_7.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.tab2.addTab(self.tabGeneral2, _fromUtf8(""))
        self.tabDetalle2 = QtGui.QWidget()
        self.tabDetalle2.setObjectName(_fromUtf8("tabDetalle2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabDetalle2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tabWidget_4 = QtGui.QTabWidget(self.tabDetalle2)
        self.tabWidget_4.setObjectName(_fromUtf8("tabWidget_4"))
        self.tabMotores2 = QtGui.QWidget()
        self.tabMotores2.setObjectName(_fromUtf8("tabMotores2"))
        self.tabWidget_4.addTab(self.tabMotores2, _fromUtf8(""))
        self.tabBaterias2 = QtGui.QWidget()
        self.tabBaterias2.setObjectName(_fromUtf8("tabBaterias2"))
        self.tabWidget_4.addTab(self.tabBaterias2, _fromUtf8(""))
        self.tabCeldas2 = QtGui.QWidget()
        self.tabCeldas2.setObjectName(_fromUtf8("tabCeldas2"))
        self.tabWidget_4.addTab(self.tabCeldas2, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget_4, 0, 0, 1, 1)
        self.tab2.addTab(self.tabDetalle2, _fromUtf8(""))
        self.tabGraficos2 = QtGui.QWidget()
        self.tabGraficos2.setObjectName(_fromUtf8("tabGraficos2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tabGraficos2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.graphicsView_4 = QtGui.QGraphicsView(self.tabGraficos2)
        self.graphicsView_4.setObjectName(_fromUtf8("graphicsView_4"))
        self.verticalLayout_3.addWidget(self.graphicsView_4)
        self.graphicsView_5 = QtGui.QGraphicsView(self.tabGraficos2)
        self.graphicsView_5.setObjectName(_fromUtf8("graphicsView_5"))
        self.verticalLayout_3.addWidget(self.graphicsView_5)
        self.graphicsView_6 = QtGui.QGraphicsView(self.tabGraficos2)
        self.graphicsView_6.setObjectName(_fromUtf8("graphicsView_6"))
        self.verticalLayout_3.addWidget(self.graphicsView_6)
        self.gridLayout_5.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tab2.addTab(self.tabGraficos2, _fromUtf8(""))
        self.tabHistorico2 = QtGui.QWidget()
        self.tabHistorico2.setObjectName(_fromUtf8("tabHistorico2"))
        self.tab2.addTab(self.tabHistorico2, _fromUtf8(""))
        self.tabBitacora2 = QtGui.QWidget()
        self.tabBitacora2.setObjectName(_fromUtf8("tabBitacora2"))
        self.tab2.addTab(self.tabBitacora2, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tab2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab1.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.tab2.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.conectarWifi.setText(_translate("MainWindow", "Conectar Wi-Fi", None))
        self.conectarXBee.setText(_translate("MainWindow", "Conectar X-Bee", None))
        self.label_47.setText(_translate("MainWindow", "Hora Partida", None))
        self.label.setText(_translate("MainWindow", "Velocidad", None))
        self.label_43.setText(_translate("MainWindow", "Crono Act.", None))
        self.label_35.setText(_translate("MainWindow", "Actual", None))
        self.label_36.setText(_translate("MainWindow", "Promedio", None))
        self.label_37.setText(_translate("MainWindow", "15 min", None))
        self.tiempo_crono_1.setDisplayFormat(_translate("MainWindow", "HH:mm:ss", None))
        self.vel_actual_1.setSuffix(_translate("MainWindow", " km/h", None))
        self.vel_prom_1.setSuffix(_translate("MainWindow", " km/h", None))
        self.vel_cuarto_1.setSuffix(_translate("MainWindow", " km/h", None))
        self.label_46.setText(_translate("MainWindow", "Crono Mod", None))
        self.label_42.setText(_translate("MainWindow", "Vel", None))
        self.label_41.setText(_translate("MainWindow", "Vel prom", None))
        self.label_44.setText(_translate("MainWindow", "E. Gastada", None))
        self.label_45.setText(_translate("MainWindow", "E. Modelo", None))
        self.label_2.setText(_translate("MainWindow", "Estrategia", None))
        self.label_3.setText(_translate("MainWindow", "Baterías", None))
        self.label_11.setText(_translate("MainWindow", "SOC", None))
        self.soc_1.setSuffix(_translate("MainWindow", " %", None))
        self.label_12.setText(_translate("MainWindow", "Voltaje", None))
        self.voltaje_1.setSuffix(_translate("MainWindow", " V", None))
        self.label_13.setText(_translate("MainWindow", "T° Max", None))
        self.T_max_baterias_1.setSuffix(_translate("MainWindow", " °C", None))
        self.label_14.setText(_translate("MainWindow", "Potencia", None))
        self.doubleSpinBox_4.setSuffix(_translate("MainWindow", " W", None))
        self.label_4.setText(_translate("MainWindow", "P. Entrada", None))
        self.label_15.setText(_translate("MainWindow", "Pot. Celdas", None))
        self.doubleSpinBox_9.setSuffix(_translate("MainWindow", " W", None))
        self.label_20.setText(_translate("MainWindow", "Temp.", None))
        self.doubleSpinBox_10.setSuffix(_translate("MainWindow", " °C", None))
        self.label_21.setText(_translate("MainWindow", "Voltaje", None))
        self.doubleSpinBox_11.setSuffix(_translate("MainWindow", " V", None))
        self.label_22.setText(_translate("MainWindow", "Corriente", None))
        self.doubleSpinBox_12.setSuffix(_translate("MainWindow", " A", None))
        self.label_5.setText(_translate("MainWindow", "P. Salida", None))
        self.label_27.setText(_translate("MainWindow", "Pot. Motor", None))
        self.potencia_motores_1.setSuffix(_translate("MainWindow", " W", None))
        self.label_28.setText(_translate("MainWindow", "T ° Max", None))
        self.T_max_motores_1.setSuffix(_translate("MainWindow", " °C", None))
        self.label_29.setText(_translate("MainWindow", "Activos", None))
        self.label_30.setText(_translate("MainWindow", "Eficiencia", None))
        self.doubleSpinBox_20.setSuffix(_translate("MainWindow", " %", None))
        self.tab1.setTabText(self.tab1.indexOf(self.tabGeneral1), _translate("MainWindow", "General", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tabMotores1), _translate("MainWindow", "Motores", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tabBaterias1), _translate("MainWindow", "Baterías", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tabCeldas1), _translate("MainWindow", "Celdas", None))
        self.tab1.setTabText(self.tab1.indexOf(self.tabDetalle1), _translate("MainWindow", "Detalle", None))
        self.tab1.setTabText(self.tab1.indexOf(self.tabGraficos1), _translate("MainWindow", "Gráficos", None))
        self.tab1.setTabText(self.tab1.indexOf(self.tabHistorico1), _translate("MainWindow", "Histórico", None))
        self.tab1.setTabText(self.tab1.indexOf(self.tabBitacora1), _translate("MainWindow", "Bitácora", None))
        self.label_64.setText(_translate("MainWindow", "Crono Act.", None))
        self.label_38.setText(_translate("MainWindow", "Actual", None))
        self.label_39.setText(_translate("MainWindow", "Promedio", None))
        self.label_40.setText(_translate("MainWindow", "15 min", None))
        self.tiempo_crono_2.setDisplayFormat(_translate("MainWindow", "HH:mm:ss", None))
        self.vel_actual_2.setSuffix(_translate("MainWindow", " km/h", None))
        self.vel_prom_2.setSuffix(_translate("MainWindow", " km/h", None))
        self.vel_cuarto_2.setSuffix(_translate("MainWindow", " km/h", None))
        self.label_6.setText(_translate("MainWindow", "Velocidad", None))
        self.label_7.setText(_translate("MainWindow", "Estrategia", None))
        self.label_59.setText(_translate("MainWindow", "Crono Mod", None))
        self.label_60.setText(_translate("MainWindow", "Vel", None))
        self.label_61.setText(_translate("MainWindow", "Vel prom", None))
        self.label_62.setText(_translate("MainWindow", "E. Gastada", None))
        self.label_63.setText(_translate("MainWindow", "E. Modelo", None))
        self.label_8.setText(_translate("MainWindow", "Baterías", None))
        self.label_16.setText(_translate("MainWindow", "SOC", None))
        self.soc_2.setSuffix(_translate("MainWindow", " %", None))
        self.label_17.setText(_translate("MainWindow", "Voltaje", None))
        self.voltaje_2.setSuffix(_translate("MainWindow", " V", None))
        self.label_18.setText(_translate("MainWindow", "T° Max", None))
        self.T_max_baterias_2.setSuffix(_translate("MainWindow", " °C", None))
        self.label_19.setText(_translate("MainWindow", "Potencia", None))
        self.doubleSpinBox_8.setSuffix(_translate("MainWindow", " W", None))
        self.label_9.setText(_translate("MainWindow", "P. Entrada", None))
        self.label_23.setText(_translate("MainWindow", "Pot. Celdas", None))
        self.doubleSpinBox_13.setSuffix(_translate("MainWindow", " W", None))
        self.label_24.setText(_translate("MainWindow", "Temp.", None))
        self.doubleSpinBox_14.setSuffix(_translate("MainWindow", " °C", None))
        self.label_25.setText(_translate("MainWindow", "Voltaje", None))
        self.doubleSpinBox_15.setSuffix(_translate("MainWindow", " V", None))
        self.label_26.setText(_translate("MainWindow", "Corriente", None))
        self.doubleSpinBox_16.setSuffix(_translate("MainWindow", " A", None))
        self.label_10.setText(_translate("MainWindow", "P. Salida", None))
        self.label_31.setText(_translate("MainWindow", "Pot. Motor", None))
        self.potencia_motores_2.setSuffix(_translate("MainWindow", " W", None))
        self.label_32.setText(_translate("MainWindow", "T ° Max", None))
        self.T_max_motores_2.setSuffix(_translate("MainWindow", " °C", None))
        self.label_33.setText(_translate("MainWindow", "Activos", None))
        self.label_34.setText(_translate("MainWindow", "Eficiencia", None))
        self.doubleSpinBox_22.setSuffix(_translate("MainWindow", " %", None))
        self.tab2.setTabText(self.tab2.indexOf(self.tabGeneral2), _translate("MainWindow", "General", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tabMotores2), _translate("MainWindow", "Motores", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tabBaterias2), _translate("MainWindow", "Baterías", None))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tabCeldas2), _translate("MainWindow", "Celdas", None))
        self.tab2.setTabText(self.tab2.indexOf(self.tabDetalle2), _translate("MainWindow", "Detalle", None))
        self.tab2.setTabText(self.tab2.indexOf(self.tabGraficos2), _translate("MainWindow", "Gráficos", None))
        self.tab2.setTabText(self.tab2.indexOf(self.tabHistorico2), _translate("MainWindow", "Histórico", None))
        self.tab2.setTabText(self.tab2.indexOf(self.tabBitacora2), _translate("MainWindow", "Bitácora", None))

